name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      - name: Generate Professional Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: yamuna-ux

          outputs: |

            dist/github-contribution-grid-snake.svg?color_snake=8B5CF6&color_dots=EEF2FF,C7D2FE,A78BFA,06B6D4,EC4899

            dist/github-contribution-grid-snake-dark.svg?color_snake=EC4899&color_dots=172554,3730A3,6D28D9,0891B2,DB2777

      - name: Publish Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
