name: Generate Colorful Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate colorful snake
        uses: Platane/snk@v3
        with:
          github_user_name: yamuna-ux
          github_token: ${{ secrets.GITHUB_TOKEN }}

          outputs: |
            dist/github-contribution-snake.svg?color_snake=%23059669&color_dots=%23EBEDF0,%23BAE6A8,%2356D364,%2339D353,%230E7C36
            dist/github-contribution-snake-dark.svg?color_snake=%2339FF88&color_dots=%23161B22,%231F7A4D,%232EA043,%2356D364,%237EE787

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
